eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: config

  #git配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/satan12345/config-repo.git
          username: 935846371@qq.com
          password: Duoluo123
          basedir: C:\Users\Administrator.SKY-20180726BRD\Desktop\local-git
  rabbitmq:
    host: 192.168.9.252
    port: 5672
    username: admin
    password: admin
    virtual-host: /



server:
  port: 8083



management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"