eureka:
  client:
    service-url:
      #注册中心地址
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
  instance:
    hostname: clientName


spring:
  application:
    name: testClient
