#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: ablejava
#    url: jdbc:mysql://192.168.9.223:3306/SpringCloud_Sell?characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
#    hikari:
#      pool-name: 商品表数据源
#      hikari.minimum-idle: 5
#      maximum-pool-size: 15
#      auto-commit: true
#      idle-timeout: 30000
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1
#  application:
#    name: product
#  jpa:
#    show-sql: true
#server:
#  port: 8081
